### ISSUE TITLE
Make the authorization ECR configurable

### ISSUE THREAD

**Issue by 2byrds** [GLEIF-IT/vlei-verifier#78]
# Tasks
- [x] Make the ECR role variable (and optionally configurable). Ideally we could provide a set of roles, rather than just one.
- [x] Modify the code so that the role is a variable, but defaults to EBA Data Submitter constant.
- [ ] Modify the test_authorizing unit test called test_ecr to prove that you can parameterize the authorizer to allow another role, in your test use the new role of "EBA Data Admin".
    - [x] You will need to modify the test data generator called get_ecr_data, adding a role parameter https://github.com/GLEIF-IT/vlei-verifier/blob/ba84a12a7a65c68ab6a2cd622be696b0fc51b42e/tests/common.py#L319
- [x] Run all tests to make sure there weren't any regressions
- [x] If you completed the optional task of modifying the configuration file and loading the configuration for ECR_Roles, then document the new configuration under the 'docs' directory in a file called CONFIGURE.md

# Introduction
The vlei-verifier handles authentication and authorization.
The vlei-verifier should be generic/configurable to eventually handle any valid vLEI use case.

Right now the only vLEI user that can complete authorization is one with an ECR (engagement context role) vLEI credential with the role of 'EBA Data Submitter'. Thats because we have been building it for the EBA pilot. However that is not generic for other vLEI users who need this verification service.

Take a look at the areas of the code that hardcoded to EBA Data Submitter right now:
- The authorizer has a constant which should become the default, rather than the only ECR role https://github.com/GLEIF-IT/vlei-verifier/blob/ba84a12a7a65c68ab6a2cd622be696b0fc51b42e/src/verifier/core/authorizing.py#L20
- The constant is used to restrict authorization to the 'EBA Data Sumbitter' https://github.com/GLEIF-IT/vlei-verifier/blob/ba84a12a7a65c68ab6a2cd622be696b0fc51b42e/src/verifier/core/authorizing.py#L192
- The common test helper assumes EBA Data Submitter for the test data https://github.com/GLEIF-IT/vlei-verifier/blob/ba84a12a7a65c68ab6a2cd622be696b0fc51b42e/tests/common.py#L323
- We only cover two test cases in the authorization ECR check:
   - by submitting an ECR_AUTH cred which is expected to fail. It isn't the ECR it is the authorization to issue an ECR. https://github.com/GLEIF-IT/vlei-verifier/blob/ba84a12a7a65c68ab6a2cd622be696b0fc51b42e/tests/core/test_authorizing.py#L77
   - by submitting an ECR cred which is expected to pass. https://github.com/GLEIF-IT/vlei-verifier/blob/ba84a12a7a65c68ab6a2cd622be696b0fc51b42e/tests/core/test_authorizing.py#L103

# Configuration
Optional bonus implementation would be to show that the service, not just the authorizer/tests can be configured.
- Note that your ECR_Roles configuration will go after the LEIs configuration here:
https://github.com/GLEIF-IT/vlei-verifier/blob/ba84a12a7a65c68ab6a2cd622be696b0fc51b42e/scripts/keri/cf/verifier-config-public.json#L32
- Note how the configuration is loaded for the LEIs configuration here, you will do similar with the ECR_roles configuration: https://github.com/GLEIF-IT/vlei-verifier/blob/ba84a12a7a65c68ab6a2cd622be696b0fc51b42e/src/verifier/core/authorizing.py#L69
- Now update the code to be able to pass the valid ecr role (or set of ecr roles) to the authorize https://github.com/GLEIF-IT/vlei-verifier/blob/ba84a12a7a65c68ab6a2cd622be696b0fc51b42e/src/verifier/core/authorizing.py#L80
